wafec:
  testing:
    driver:
      openstack:
        client:
          flavors: "http://localhost:5000/api/nova/flavors/"
          images: "http://localhost:5000/api/glance/images/"
          servers: "http://localhost:5000/api/nova/servers/"
          volumes: "http://localhost:5000/api/cinder/volumes/"
          networks: "http://localhost:5000/api/neutron/networks/"
    support:
      rabbitmq:
        management:
          client:
            username: "openstack"
            password: "supersecret"
            url: "http://controller:15672/api"
        connection:
          username: "openstack"
          password: "supersecret"
          host: "controller"
          port: 5672
    core:
      analysis:
        json-builder: no